#@data/values-schema
---
cloudwatch_log_group_arn: ""
cloudwatch_start_position: "end"

elasticsearch:
  #@schema/default ["elasticsearch:9200"]
  hosts: [""]
  protocol: "https"
  username: ""
  password: ""

#@schema/type any=True
setup:
  template:
    name: "filebeat-%{[agent.version]}"
    overwrite: true
  ilm:
    enabled: true
    policy_name: "filebeat"
    overwrite: true

#@schema/type any=True
modules:

#@schema/type any=True
xpack:

#@schema/type any=True
logging:
