#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
filebeat.config.inputs:
#@ if data.values.cloudwatch_log_group_arn != "":
  - type: aws-cloudwatch
    log_group_arn: #@ data.values.cloudwatch_log_group_arn
    start_position: #@ data.values.cloudwatch_start_position
#@ end

output.elasticsearch: #@ data.values.elasticsearch

#@ if/end data.values.modules:
filebeat.modules: #@ data.values.modules

#@ if/end data.values.setup:
setup: #@ data.values.setup

#@ if/end data.values.xpack:
xpack: #@ data.values.xpack

#@ if/end data.values.logging:
logging: #@ data.values.logging
