name: Build and Push Custom Filebeat Image

on:
  push:
    branches:
      - 1.x
    tags:
      - "v*.*.*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filebeat_version: ["7.17.8", "8.6.2"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/filebeat-for-cloudwatch
          tags: |
            latest=false
            type=semver,pattern={{version}},prefix=${{ matrix.filebeat_version }}-
            type=semver,pattern={{major}}.{{minor}},prefix=${{ matrix.filebeat_version }}-
            type=semver,pattern={{major}},prefix=${{ matrix.filebeat_version }}-
            type=ref,event=branch,prefix=${{ matrix.filebeat_version }}

      - name: Build and push custom Filebeat image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            FILEBEAT_VERSION=${{ matrix.filebeat_version }}
          platforms: linux/amd64,linux/arm64
          # GitHub Actions Caches
          # https://docs.docker.com/build/cache/backends/gha/#using-dockerbuild-push-action
          cache-from: type=gha
          cache-to: type=gha,mode=max
